/* LISTA DE EXERCÍCIOS - REVISÃO CP 1

2. ESCREVA UM BLOCO PL/SQL QUE RECEBA UM NÚMERO PELO TECLADO E RETORNE
"PAR" SE O NÚMERO FOR "PAR" E "ÍMPAR" SE NÚMERO FOR ÍMPAR*/

SET SERVEROUTPUT ON;

DECLARE
    V_NUMERO INT;

BEGIN
        -- SOLICITA O USUÁRIO O NÚMERO
        DBMS_OUTPUT.PUT_LINE('INSIRA UM NÚMERO: ');
        V_NUMERO := &NUMERO;
        
        -- VERIFICA SE O NÚMERO É PAR OU ÍMPAR
        IF MOD (V_NUMERO, 2) = 0 THEN
            DBMS_OUTPUT.PUT_LINE('O NÚMERO INFORMADO É PAR');
        ELSE 
            DBMS_OUTPUT.PUT_LINE('O NÚMERO INFORMADO É ÍMPAR');
        END IF;    
END;
/