/* LISTA DE EXERCÍCIOS - REVISÃO CP 1

3. DESENVOLVA UM BLOCO PL/SQL QUE UTILIZE UM LOOP WHILE PARA CALCULAR A SOMA
DOS NÚMEROS DE 1 A 100*/

SET SERVEROUTPUT ON;

DECLARE
    V_SOMA_TOTAL NUMBER(10) := 0;
    V_CONTADOR NUMBER(10) := 1;
BEGIN
        -- CONDIÇÕES: PRÉ
        WHILE V_CONTADOR <= 100 LOOP
        -- INSTRUÇÕES
        V_SOMA_TOTAL := V_SOMA_TOTAL + V_CONTADOR;
        V_CONTADOR := V_CONTADOR +1;
    END LOOP;      
    DBMS_OUTPUT.PUT_LINE ('A SOMA DOS NÚMEROS DE 1 A 100 É: ' || V_SOMA_TOTAL);
END;
/