/*20. Implemente uma tabela chamada "ESTQOUE_PRODUTOS" com colunas
"PRODUTO", "ESTOQUE", "OBS". Escreva um bloco PL/SQL que verifique se o
estoque de um produto está abaixo do limite mínimo de 5. Se estiver, exiba
uma mensagem utilizando dbms_output e insira a informação na tabela
"ESTOQUE_PRODUTOS" no campo "OBS".*/

SET SERVEROUTPUT ON;

DROP TABLE ESTOQUE_PRODUTOS;
CREATE TABLE ESTOQUE_PRODUTOS (
    PRODUTO VARCHAR2(100),
    ESTOQUE INTEGER,
    OBS VARCHAR(200)
);

INSERT INTO ESTOQUE_PRODUTOS (PRODUTO, ESTOQUE) VALUES ('Arroz', 10);
INSERT INTO ESTOQUE_PRODUTOS (PRODUTO, ESTOQUE) VALUES ('Feijão', 7);
INSERT INTO ESTOQUE_PRODUTOS (PRODUTO, ESTOQUE) VALUES ('Açúcar', 6);
INSERT INTO ESTOQUE_PRODUTOS (PRODUTO, ESTOQUE) VALUES ('Sal', 3);
INSERT INTO ESTOQUE_PRODUTOS (PRODUTO, ESTOQUE) VALUES ('Óleo', 4);

DECLARE
    V_PRODUTO ESTOQUE_PRODUTOS.PRODUTO%TYPE := '&DIGITE_NOME_PRODUTO';
    V_ESTOQUE ESTOQUE_PRODUTOS.ESTOQUE%TYPE;
    V_OBS ESTOQUE_PRODUTOS.OBS%TYPE;
BEGIN
    -- Obtém o estoque do produto
    SELECT ESTOQUE INTO V_ESTOQUE
    FROM ESTOQUE_PRODUTOS
    WHERE PRODUTO = V_PRODUTO;
    
    -- Verifica se o estoque está abaixo do limite mínimo
    IF V_ESTOQUE < 5 THEN
        V_OBS := 'ESTOQUE ABAIXO DO LIMITE DE 5.';
        
        -- Insere a informação na tabela ESTOQUE_PRODUTOS
        UPDATE ESTOQUE_PRODUTOS
        SET OBS = V_OBS
        WHERE PRODUTO = V_PRODUTO;
        
        -- Exibe uma mensagem
        DBMS_OUTPUT.PUT_LINE('O ESTOQUE DO PRODUTO ' || V_PRODUTO || ' ESTÁ ABAIXO DO LIMITE MÍNIMO. A OBSERVAÇÃO FOI COLOCADA NA TABELA ESTOQUE_PRODUTOS.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('O ESTOQUE DO PRODUTO ' || V_PRODUTO || ' ESTÁ ACIMA DO LIMITE MÍNIMO.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('PRODUTO NÃO ENCONTRADO NA TABELA ESTOQUE_PRODUTOS.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OCORREU UM ERRO AO PROCESSAR A SOLICITAÇÃO.');
END;
/

