/* LISTA DE EXERCÍCIOS - REVISÃO CP 1

1. CRIE UM BLOCO PL/SQL QUE UTILIZE UM LOOP FOR PARA EXIBIR OS NÚMEROS 
DE 1 A 10 */

SET SERVEROUTPUT ON;

DECLARE
    V_INICIO NUMBER(2) := 1;
    V_FIM NUMBER(2) := 10;

BEGIN
    LOOP
        -- INSTRUÇÕES
        DBMS_OUTPUT.PUT_LINE(V_INICIO);
        V_INICIO := V_INICIO + 1;
        -- CONDIÇÃO
        EXIT WHEN (V_INICIO > V_FIM);
    END LOOP;    
    
END;