/* 12.Implemente uma coluna "Data_Modificacao". Escreva um bloco
PL/SQL que atualize o campo "Data_Modificacao" enviada pelo teclado na
tabela "FUNCIONARIOS_SEM3".*/


SET SERVEROUTPUT ON;

ALTER TABLE FUNCIONARIO_SEM3 ADD (DATA_MODIFICACAO DATE);

DECLARE
    V_DATA_MODIFICACAO DATE := TO_DATE('&DATA_MODIFICACAO', 'DD/MM/YYYY'); 
BEGIN
    UPDATE FUNCIONARIO_SEM3
    SET DATA_MODIFICACAO = V_DATA_MODIFICACAO;
    
    -- Exibe mensagem de confirmação
    DBMS_OUTPUT.PUT_LINE('DATA DE MODIFICACAO ATUALIZADA COM SUCESSO PARA: ' || V_DATA_MODIFICACAO);
END;
/

SELECT * FROM FUNCIONARIO_SEM3;
