/* LISTA DE EXERCÍCIOS - REVISÃO CP 1

5. Crie um bloco PL/SQL que calcule o fatorial de um número usando um
loop FOR.
*/

SET SERVEROUTPUT ON;

DECLARE
    V_NUMERO INTEGER := &NUMERO; -- SOLICITA O NUMERO PARA O USUARIO
    V_FATORIAL INTEGER := 1;
    
BEGIN   
    -- VERIFICA SE O NUMERO É NEGATIVO
    IF V_NUMERO < 0 THEN
        DBMS_OUTPUT.PUT_LINE('NÃO É POSSÍVEL CALCULAR O FATORIAL DE UM NÚMERO NEGATIVO.');
    ELSE
    -- CALCULA FATORIAL
        FOR I IN 1..V_NUMERO LOOP
            V_FATORIAL := V_FATORIAL * I;
        END LOOP;
    -- RESULTADO
    DBMS_OUTPUT.PUT_LINE('O FATORIAL DE ' || V_NUMERO || ' É ' || V_FATORIAL);
    END IF;
END;
/
